fullname = input("Enter your Full name:")
age = int(input("Enter your Age:"))
start_year = int(input("Enter your Start year:"))
pass_out = int(input("Enter your Pass-out year:"))
college = input("Enter your collge name:")
print("-----------------------------------------------------------")
print("Full Name:",fullname)
print("Age:",age)
print("Passout: [",start_year,"-",pass_out,"]")
print("College name:",college)